[package]
name = "sukaku-forge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sukaku-forge-core = { path = "../core" }
sukaku-forge-engine = { path = "../engine" }

[lints]
workspace = true

[[bin]]
name = "sukaku-forge"
path = "src/main.rs"
